// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "取得所有使用者",
                "responses": {}
            },
            "post": {
                "description": "新增一筆使用者資料",
                "tags": [
                    "users"
                ],
                "summary": "建立使用者",
                "parameters": [
                    {
                        "description": "使用者資料",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserRq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/users/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "取得單一使用者",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "更新使用者",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "使用者資料",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "刪除使用者",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "user.CreateUserRq": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "description": "使用者 Email",
                    "type": "string",
                    "example": "leo@example.com"
                },
                "name": {
                    "description": "使用者名稱",
                    "type": "string",
                    "example": "Leo"
                }
            }
        },
        "user.User": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "createdAt": {
                    "description": "建立時間",
                    "type": "string",
                    "example": "2025-05-13T12:00:00Z"
                },
                "email": {
                    "description": "使用者 Email",
                    "type": "string",
                    "example": "leo@example.com"
                },
                "id": {
                    "description": "使用者 ID",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "使用者名稱",
                    "type": "string",
                    "example": "Leo"
                },
                "updatedAt": {
                    "description": "最後更新時間",
                    "type": "string",
                    "example": "2025-05-13T12:30:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8088",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Go CRUD API",
	Description:      "GO語言  CRUD_TEST",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
